import 'package:flutter/material.dart';
// import 'package:firebase_core/firebase_core.dart';
import 'theme/app_theme.dart';
import 'screens/welcome_screen.dart';
import 'screens/dashboard_screen.dart';
import 'screens/law_map_screen.dart';
import 'screens/ocr_scanner_screen.dart';
import 'screens/case_synopsis_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Firebase initialization (using default options for now, usually requires firebase_options.dart)
  // await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  // For now, we comment it out as we don't have the configuration file generated by FlutterFire CLI.

  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'NyayaAssist',
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: ThemeMode.system,
      initialRoute: '/',
      routes: {
        '/': (context) => const WelcomeScreen(),
        '/dashbord': (context) => const DashboardScreen(),
        '/law_map': (context) => const LawMapScreen(),
        '/ocr': (context) => const OCRScannerScreen(),
        '/synopsis': (context) => const CaseSynopsisScreen(),
      },
    );
  }
}
