import 'package:flutter/material.dart';
// import 'package:firebase_core/firebase_core.dart';
import 'theme/app_theme.dart';
import 'screens/welcome_screen.dart';
import 'screens/main_layout.dart';
import 'screens/law_map_screen.dart';
import 'screens/case_synopsis_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Firebase initialization (using default options for now, usually requires firebase_options.dart)
  // await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  // For now, we comment it out as we don't have the configuration file generated by FlutterFire CLI.

  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'NyayaAssist',
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: ThemeMode.system,
      initialRoute: '/',
      onGenerateRoute: (settings) {
        if (settings.name == '/law_map') {
          final query = settings.arguments as String?;
          return MaterialPageRoute(
            builder: (context) => LawMapScreen(initialQuery: query),
          );
        }
        return null;
      },
      routes: {
        '/': (context) => const WelcomeScreen(),
        '/dashbord': (context) => const MainLayout(),
        '/synopsis': (context) => const CaseSynopsisScreen(),
      },
    );
  }
}
